### ISSUE TITLE
Support for RGB, and custom GUI

### ISSUE THREAD

**Issue by Misio12320** [sarhatabaot/EnchantGUI#8]
Hi. Can you add RGB support for the GUI and allow to customize the GUI?

**Comment by sarhatabaot** [comment]
You can customize the gui already. Gui is customizable via shop.yml
I'll look into adding RGB support.

**Comment by Misio12320** [comment]
Also add support for lore in GUI and button back-item: "DIAMOND" NAMED "" with a lore "".

**Comment by sarhatabaot** [comment]
What do you mean purchase custom items? EnchantGUI is just for enchants. You can already customize the back item by changing the `back-item:` entry. 
Do you mean adding additional lore to the back item?

**Comment by Misio12320** [comment]
> What do you mean purchase custom items? EnchantGUI is just for enchants.

Well true, okay.


> Do you mean adding additional lore to the back item?

Yeah would be cool I think.
And add support to make custom GUI I mean custom rows like 6 rows and fill the empty slots with something and
slot1: "diamond sword" with sharpness <- and it will open the GUI with sharpness shop for player's sword/axe
slot2: "diamond chestplate" with protection with lore "PROTECTION" and it should open shop with protection 🤔

**Comment by Misio12320** [comment]
@sarhatabaot

**Comment by sarhatabaot** [comment]
EnchantGUI isn't meant to support purchasing custom items. Use something like ChestCommands or BossShopPro if you want more functionality with guis.
I'll add RGB support in the future, with better back item configuration.
